version: "3.9"


services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.3"
    container_name: booking_php
    working_dir: /var/www/html/api
    volumes:
      - ./:/var/www/html:delegated
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=booking"
      XDEBUG_CLIENT_HOST: host.docker.internal
      SYMFONY_PHPUNIT_VERSION: 10
      COMPOSER_HOME: /tmp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    image: nginx:1.27-alpine
    container_name: booking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 10


  db:
    image: postgres:16-alpine
    container_name: booking_db
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking -d booking"]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: booking_redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: booking_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "5173:5173" # Vite dev server
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    depends_on:
      nginx:
        condition: service_started

volumes:
  pgdata:
  node_modules: