framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: allow_no_handlers
            query.bus:
                default_middleware: allow_no_handlers
