<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251001171322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reservation_dates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, price NUMERIC(10, 2) NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E80B19B9B83297E7 ON reservation_dates (reservation_id)');
        $this->addSql('CREATE INDEX IDX_E80B19B9AA9E377A ON reservation_dates (date)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E80B19B9B83297E7AA9E377A ON reservation_dates (reservation_id, date)');
        $this->addSql('CREATE TABLE reservations (id UUID NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, guest_name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, status VARCHAR(16) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, room_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DA239296E3073 ON reservations (room_type_id)');
        $this->addSql('CREATE INDEX IDX_4DA23995275AB8 ON reservations (start_date)');
        $this->addSql('CREATE INDEX IDX_4DA239845CBB3E ON reservations (end_date)');
        $this->addSql('CREATE INDEX IDX_4DA2397B00651C ON reservations (status)');
        $this->addSql('CREATE INDEX IDX_4DA239E7927C74 ON reservations (email)');
        $this->addSql('CREATE TABLE room_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_138C289B5E237E06 ON room_types (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_138C289B77153098 ON room_types (code)');
        $this->addSql('CREATE INDEX IDX_138C289B5E237E06 ON room_types (name)');
        $this->addSql('CREATE INDEX IDX_138C289B77153098 ON room_types (code)');
        $this->addSql('CREATE TABLE vacancy_calendar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, capacity_total INT NOT NULL, capacity_available INT NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, room_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C39B77FAA9E377A ON vacancy_calendar (date)');
        $this->addSql('CREATE INDEX IDX_1C39B77F296E3073 ON vacancy_calendar (room_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C39B77FAA9E377A296E3073 ON vacancy_calendar (date, room_type_id)');
        $this->addSql('ALTER TABLE reservation_dates ADD CONSTRAINT FK_E80B19B9B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239296E3073 FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vacancy_calendar ADD CONSTRAINT FK_1C39B77F296E3073 FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reservation_dates DROP CONSTRAINT FK_E80B19B9B83297E7');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239296E3073');
        $this->addSql('ALTER TABLE vacancy_calendar DROP CONSTRAINT FK_1C39B77F296E3073');
        $this->addSql('DROP TABLE reservation_dates');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE room_types');
        $this->addSql('DROP TABLE vacancy_calendar');
    }
}
